create table person
(
    person_id int generated by default as identity primary key,
    name      varchar(100) not null unique,
    year      int          not null
);

create table book
(
    book_id   int generated by default as identity primary key,
    title     varchar not null,
    author    varchar not null,
    year      int     not null,
    person_id int references person (person_id) on delete set null
);

insert into person(name, year)
values ('Иванов Иван Иванович', 1970),
       ('Петров Петр Петрович', 1960),
       ('Алексеев Алексей Алексеевич', 1989),
       ('Познер Владимир Владимирович', 1944),
       ('Федоров Мирон Янович', 1985);

insert into book(title, author, year)
values ('Над пропастью во ржи', 'Джером Сэринджер', 1951),
       ('День опричника', 'Владимир Сорокин', 2006),
       ('Тайные виды на гору Фудзи', 'Владимир Пелевин', 2018);
